import React from 'react';
import HeroGrid from '@/components/HeroGrid';

type Props = {};

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

const About = (props: Props) => {
  return (
    <div className='mt-[60px]'>
      <div className='container'>
        <HeroGrid />
        <div className='mt-6'>
          <h2 className='font-bold'>เกี่ยวกับเรา</h2>
          <div className='flex flex-col md:flex-row justify-between gap-4'>
            <p className=' max-w-sm text-primary'>
              ตำบลบางปู เล่ากันว่าหมู่บ้านแห่งนี้เดิมๆอยู่ริมทะเล
              (อ่าว)ในทะเลมีปลาชุกชุมชาวบ้านประกอบอาชีพประมงน้ำตื้น
              ทุกครอบครัวจะมีเรือและเครื่องมือจับปลาลักษณะเดี๋ยวนี้ก็ยังมีอยู่{' '}
            </p>
            <p>
              ตำบลบางปู เล่ากันว่าหมู่บ้านแห่งนี้เดิมๆอยู่ริมทะเล
              (อ่าว)ในทะเลมีปลาชุกชุมชาวบ้านประกอบอาชีพประมงน้ำตื้น
              ทุกครอบครัวจะมีเรือและเครื่องมือจับปลาลักษณะเดี๋ยวนี้ก็ยังมีอยู่{' '}
            </p>
          </div>
        </div>
        <div className='flex flex-col md:flex-row gap-4 mt-6'>
          <div className='flex-[50%] aspect-video bg-zinc-100' />
          <div className='flex-[50%] aspect-video bg-zinc-100' />
        </div>
      </div>
    </div>
  );
};

export default About;
