import RootStyleRegistry from './emotion';
import './globals.css';
import './base.css';
import { Anuphan } from 'next/font/google';
import Header from './Header';
import Footer from './Footer';
import Providers from '@/components/Providers';

const anuphan = Anuphan({ subsets: ['thai'] });

export const metadata = {
  title: 'Pattani smart tourism',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Pattani smart tourism',
    description: 'Generated by create next app',
    url: 'https://triple-i.in',
    siteName: 'Pattani smart tourism',
    publishedTime: '2023-01-01T00:00:00.000Z',
    authors: ['triple-i'],
    images: [
      {
        url: './vercel.svg',
        width: 800,
        height: 600,
      },
      {
        url: './vercel.svg',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default async function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={anuphan.className}>
        <RootStyleRegistry>
          <Providers>
            <Header />
            {authModal}
            <main className='md:min-h-[calc(100vh-83px)] min-h-[calc(100vh-122.8px)] bg-[rgb(248, 249, 250)]'>
              {children}
            </main>
            <Footer />
          </Providers>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
