import TravelTabs from '@/components/AccountTabs';
import TravelList from '@/components/TravelList';
import TravelSearch from '@/components/TravelSearch';
import { Tabs } from '@mantine/core';
import React from 'react';

type Props = {};

export const metadata = {
  title: 'Travel',
  description: 'Generated by create next app',
};

const Page = (props: Props) => {
  return (
    <div className='mt-24'>
      <div className='container'>
        <h1 className='text-center'>รายการท่องเที่ยว</h1>
        <TravelSearch className='mt-6' />
        <TravelList className='mt-6' />
      </div>
    </div>
  );
};

export default Page;
