import AccountTabs from '@/components/AccountTabs';
import React from 'react';

type Props = {};

export const metadata = {
  title: 'Account',
  description: 'Generated by create next app',
};

const Page = (props: Props) => {
  return (
    <div>
      <div className='container'>
        <h1 className='text-center mt-20'>ข้อมูลส่วนตัว</h1>
        <AccountTabs className='mt-4' />
      </div>
    </div>
  );
};

export default Page;
